# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QSlider,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1680, 1020)
        MainWindow.setMinimumSize(QSize(1680, 1020))
        MainWindow.setMaximumSize(QSize(1680, 1020))
        font = QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.result_img = QLabel(self.centralwidget)
        self.result_img.setObjectName(u"result_img")
        self.result_img.setGeometry(QRect(10, 10, 1440, 1000))
        self.result_img.setFrameShape(QFrame.Shape.Panel)
        self.save_button = QPushButton(self.centralwidget)
        self.save_button.setObjectName(u"save_button")
        self.save_button.setGeometry(QRect(1460, 130, 200, 80))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setItalic(False)
        font1.setUnderline(False)
        self.save_button.setFont(font1)
        self.load_button = QPushButton(self.centralwidget)
        self.load_button.setObjectName(u"load_button")
        self.load_button.setEnabled(True)
        self.load_button.setGeometry(QRect(1460, 50, 200, 80))
        self.load_button.setFont(font1)
        self.reset_button = QPushButton(self.centralwidget)
        self.reset_button.setObjectName(u"reset_button")
        self.reset_button.setGeometry(QRect(1460, 210, 200, 80))
        self.reset_button.setFont(font1)
        self.draw_button = QPushButton(self.centralwidget)
        self.draw_button.setObjectName(u"draw_button")
        self.draw_button.setGeometry(QRect(1460, 340, 200, 80))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        self.draw_button.setFont(font2)
        self.fft_button = QPushButton(self.centralwidget)
        self.fft_button.setObjectName(u"fft_button")
        self.fft_button.setGeometry(QRect(1460, 430, 200, 80))
        self.fft_button.setFont(font2)
        self.H_min_Slider = QSlider(self.centralwidget)
        self.H_min_Slider.setObjectName(u"H_min_Slider")
        self.H_min_Slider.setGeometry(QRect(1470, 552, 160, 30))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.H_min_Slider.sizePolicy().hasHeightForWidth())
        self.H_min_Slider.setSizePolicy(sizePolicy)
        self.H_min_Slider.setMaximum(255)
        self.H_min_Slider.setValue(0)
        self.H_min_Slider.setOrientation(Qt.Orientation.Horizontal)
        self.H_max_Slider = QSlider(self.centralwidget)
        self.H_max_Slider.setObjectName(u"H_max_Slider")
        self.H_max_Slider.setGeometry(QRect(1470, 572, 160, 30))
        sizePolicy.setHeightForWidth(self.H_max_Slider.sizePolicy().hasHeightForWidth())
        self.H_max_Slider.setSizePolicy(sizePolicy)
        self.H_max_Slider.setMaximum(255)
        self.H_max_Slider.setValue(0)
        self.H_max_Slider.setOrientation(Qt.Orientation.Horizontal)
        self.S_min_Slider = QSlider(self.centralwidget)
        self.S_min_Slider.setObjectName(u"S_min_Slider")
        self.S_min_Slider.setGeometry(QRect(1470, 592, 160, 30))
        sizePolicy.setHeightForWidth(self.S_min_Slider.sizePolicy().hasHeightForWidth())
        self.S_min_Slider.setSizePolicy(sizePolicy)
        self.S_min_Slider.setMaximum(255)
        self.S_min_Slider.setOrientation(Qt.Orientation.Horizontal)
        self.S_max_Slider = QSlider(self.centralwidget)
        self.S_max_Slider.setObjectName(u"S_max_Slider")
        self.S_max_Slider.setGeometry(QRect(1470, 612, 160, 30))
        sizePolicy.setHeightForWidth(self.S_max_Slider.sizePolicy().hasHeightForWidth())
        self.S_max_Slider.setSizePolicy(sizePolicy)
        self.S_max_Slider.setMaximum(255)
        self.S_max_Slider.setOrientation(Qt.Orientation.Horizontal)
        self.V_min_Slider = QSlider(self.centralwidget)
        self.V_min_Slider.setObjectName(u"V_min_Slider")
        self.V_min_Slider.setGeometry(QRect(1470, 632, 160, 30))
        sizePolicy.setHeightForWidth(self.V_min_Slider.sizePolicy().hasHeightForWidth())
        self.V_min_Slider.setSizePolicy(sizePolicy)
        self.V_min_Slider.setMaximum(255)
        self.V_min_Slider.setOrientation(Qt.Orientation.Horizontal)
        self.V_max_Slider = QSlider(self.centralwidget)
        self.V_max_Slider.setObjectName(u"V_max_Slider")
        self.V_max_Slider.setGeometry(QRect(1470, 652, 160, 30))
        sizePolicy.setHeightForWidth(self.V_max_Slider.sizePolicy().hasHeightForWidth())
        self.V_max_Slider.setSizePolicy(sizePolicy)
        self.V_max_Slider.setMaximum(255)
        self.V_max_Slider.setOrientation(Qt.Orientation.Horizontal)
        self.H_min_label = QLabel(self.centralwidget)
        self.H_min_label.setObjectName(u"H_min_label")
        self.H_min_label.setGeometry(QRect(1635, 559, 31, 16))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(30)
        sizePolicy1.setHeightForWidth(self.H_min_label.sizePolicy().hasHeightForWidth())
        self.H_min_label.setSizePolicy(sizePolicy1)
        self.H_min_label.setMidLineWidth(4)
        self.H_max_label = QLabel(self.centralwidget)
        self.H_max_label.setObjectName(u"H_max_label")
        self.H_max_label.setGeometry(QRect(1635, 579, 31, 16))
        sizePolicy1.setHeightForWidth(self.H_max_label.sizePolicy().hasHeightForWidth())
        self.H_max_label.setSizePolicy(sizePolicy1)
        self.H_max_label.setMidLineWidth(4)
        self.S_min_label = QLabel(self.centralwidget)
        self.S_min_label.setObjectName(u"S_min_label")
        self.S_min_label.setGeometry(QRect(1635, 599, 31, 16))
        sizePolicy1.setHeightForWidth(self.S_min_label.sizePolicy().hasHeightForWidth())
        self.S_min_label.setSizePolicy(sizePolicy1)
        self.S_min_label.setMidLineWidth(4)
        self.S_max_label = QLabel(self.centralwidget)
        self.S_max_label.setObjectName(u"S_max_label")
        self.S_max_label.setGeometry(QRect(1635, 619, 31, 16))
        sizePolicy1.setHeightForWidth(self.S_max_label.sizePolicy().hasHeightForWidth())
        self.S_max_label.setSizePolicy(sizePolicy1)
        self.S_max_label.setMidLineWidth(4)
        self.V_min_label = QLabel(self.centralwidget)
        self.V_min_label.setObjectName(u"V_min_label")
        self.V_min_label.setGeometry(QRect(1635, 639, 31, 16))
        sizePolicy1.setHeightForWidth(self.V_min_label.sizePolicy().hasHeightForWidth())
        self.V_min_label.setSizePolicy(sizePolicy1)
        self.V_min_label.setMidLineWidth(4)
        self.V_max_label = QLabel(self.centralwidget)
        self.V_max_label.setObjectName(u"V_max_label")
        self.V_max_label.setGeometry(QRect(1635, 660, 31, 16))
        sizePolicy1.setHeightForWidth(self.V_max_label.sizePolicy().hasHeightForWidth())
        self.V_max_label.setSizePolicy(sizePolicy1)
        self.V_max_label.setMidLineWidth(4)
        self.default_button = QPushButton(self.centralwidget)
        self.default_button.setObjectName(u"default_button")
        self.default_button.setGeometry(QRect(1460, 680, 200, 80))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(30)
        sizePolicy2.setHeightForWidth(self.default_button.sizePolicy().hasHeightForWidth())
        self.default_button.setSizePolicy(sizePolicy2)
        self.default_button.setFont(font1)
        self.count_button = QPushButton(self.centralwidget)
        self.count_button.setObjectName(u"count_button")
        self.count_button.setGeometry(QRect(1460, 770, 200, 200))
        sizePolicy2.setHeightForWidth(self.count_button.sizePolicy().hasHeightForWidth())
        self.count_button.setSizePolicy(sizePolicy2)
        font3 = QFont()
        font3.setPointSize(20)
        font3.setBold(True)
        font3.setItalic(False)
        font3.setUnderline(False)
        self.count_button.setFont(font3)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(1462, 14, 191, 31))
        font4 = QFont()
        font4.setPointSize(15)
        font4.setBold(True)
        font4.setItalic(False)
        self.label.setFont(font4)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1460, 300, 191, 31))
        self.label_2.setFont(font4)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(1460, 520, 191, 31))
        self.label_3.setMinimumSize(QSize(191, 31))
        self.label_3.setMaximumSize(QSize(191, 31))
        self.label_3.setFont(font4)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1680, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Cell Count", None))
        self.result_img.setText("")
        self.save_button.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u56fe\u50cf", None))
        self.load_button.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u56fe\u50cf", None))
        self.reset_button.setText(QCoreApplication.translate("MainWindow", u"\u6062\u590d\u539f\u56fe", None))
        self.draw_button.setText(QCoreApplication.translate("MainWindow", u"\u7070\u5ea6\u76f4\u65b9\u56fe", None))
        self.fft_button.setText(QCoreApplication.translate("MainWindow", u"\u5085\u91cc\u53f6\u9891\u8c31", None))
        self.H_min_label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.H_max_label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.S_min_label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.S_max_label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.V_min_label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.V_max_label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.default_button.setText(QCoreApplication.translate("MainWindow", u"\u6062\u590d\u9ed8\u8ba4\u53c2\u6570", None))
        self.count_button.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u8ba1\u6570", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u57fa\u7840\u64cd\u4f5c", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7edf\u8ba1", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u53c2\u6570\u8bbe\u7f6e", None))
    # retranslateUi

